ArslanYM/StarterHive

- README.md
Worked on #15.
Added a new step which tells the contributor to make the changes as per their picked issue/feature before adding to staging.
> adding new step under steps to contribute

- README.md
#20
Added appropriate folder and file naming convention commonly used in React projects.
> fix: file extension and folder naming convention

- ISSUES/issues.md
- README.md
#23
- added a directory name "ISSUES" and create a issues.md file inside it.
> added ISSUES directory and issues.md

- README.md
#14 
Edit readme.md to add a short thanks message for contributors and add a link to CONTRIBUTORS.MD
> Add contributors thanks message

- CONTRIBUTORS.md
Updates my name in the CONTRIBUTORS.md
> Updated name

- web/package-lock.json
- web/package.json
- web/src/App.jsx
- web/src/components/DummyComponent.jsx
- web/src/components/index.js
- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
- web/src/layouts/Hero.jsx
- web/src/layouts/MasterLayout.jsx
- web/src/layouts/index.js
- web/src/pages/About.jsx
- web/src/pages/Home.jsx
- web/src/pages/index.js
Issue #38
- Added folder structure as per the issue.
- Setup the routing and layout structure.
> feat: folder structure improvements

- web/package-lock.json
- web/package.json
- web/src/layouts/Header.jsx
#50 
I have added GitHub svg Icon to GitHub button in the header, and I linked this button to the link of the repo.
> Add GitHub icon to header

- CONTRIBUTORS.md
- web/src/layouts/Footer.jsx
With reference to Issue https://github.com/ArslanYM/StarterHive/issues/58,
I have used react-icons library for the icons and added the links in the anchor tags. All the links and the icons were checked by locally deploying the project and confirmed to be working.
Icons were added in the manner stated in the issue. 
modified:   CONTRIBUTORS.md
modified:   web/src/layouts/Footer.jsx
> Added Icons on footer section with hyperlinks on click.

- CONTRIBUTORS.md
- Added new name and GitHub profile
> Update and added new name in CONTRIBUTORS.md

- web/src/layouts/Hero.jsx
This pull request has changes to the hero layout to fix the picture loading issue.
I have imported the image and updated the value in the source of the image tag.
> Fix image loading issue in hero section

- CONTRIBUTORS.md
- web/src/layouts/Footer.jsx
- web/yarn.lock
-> Added tailwind classes to increase size (same size as header github SVG)   `text-2xl `
-> Added hover effect using `hover:fill-violet-500`  
-> Used unique fill color on hover of each svg
In-All changes in svg icons:
`<FaDiscord className="text-2xl duration-300 hover:fill-violet-500" />`
Finally, increased the margin-left on icons: `ml-5`
Result:
Hover colors:
> increased footer SVG sizes and added hover effects with respective colors

- web/src/layouts/Header.jsx
Added a small arrow beside the GitHub icon as the issue described
> Added small arrow

- CONTRIBUTORS.md
> added my profile in contributers list

- GUIDELINES.md
Fixes: [Issue#19](https://github.com/ArslanYM/StarterHive/issues/19)
Resolution: Swapped the python style guide for JS style guide by AirBnB for the hyperlink "coding style" @line-no:9
Description:
The initial intent was to redirect to a JS style guide, but the style guide provided in the hyperlink was a Python one.
So edited the hyperlink
> Updated JS Style guide Hyperlink @GUIDELINES.md

- web/src/layouts/Header.jsx
- web/yarn.lock
Fixes https://github.com/ArslanYM/StarterHive/issues/94
Bug fix
Adds tailwind class cursor-pointer to navbar in header so that pointer shows when we hover over them
___
**How should this be tested?**
> #94 navbar cursor pointer fixes

- web/src/layouts/Hero.jsx
What does this PR do?
Fixes https://github.com/ArslanYM/StarterHive/issues/103
Type of change
Bug fix
Adds tailwind class to the Find issues button so that it appears to be floating upward direction when hover over
[screen-capture.webm](https://github.com/ArslanYM/StarterHive/assets/12849916/6d0e1d90-11cc-4260-bc31-2d1b5b1dffb6)
> feat: floating action added to Find Issues button

- web/src/components/Heroimg.jsx
- web/src/layouts/Hero.jsx
- web/yarn.lock
FEAT: Add images to the hero divs  #102
> add more images in div

- web/src/layouts/Header.jsx
- web/src/layouts/Hero.jsx
- web/tailwind.config.js
Fixes https://github.com/ArslanYM/StarterHive/issues/110
Type of change
Bug fix
Adds tailwind custom utility class to animate div like floating 
[screen-capture.webm](https://github.com/ArslanYM/StarterHive/assets/12849916/e1b4e987-fe37-42c8-86c9-48134a59a8db)
> fix: animate floating divs

- web/src/layouts/Header.jsx
Fixes https://github.com/ArslanYM/StarterHive/issues/108
Type of change
Bug fix  navbar left alignment fixes
> fix: navbar left alignment fixes

- web/src/components/HeroImage.jsx
- web/src/pages/Home/Home.jsx
bug fix
floating divs get their size back
> fix: floating divs restored

- package-lock.json
- web/src/pages/Contributors/ContributorItem.jsx
- web/src/pages/Contributors/Contributors.jsx
- web/src/pages/Contributors/ContributorsList.jsx
haven't made any major changes, refactored the code and added thanking message
kindly review the changes
> refactored contributors page

- web/src/layouts/Header.jsx
- web/src/pages/Home/Home.jsx
bug fixes
floating divs are back
header and hero is aligned together
> rahilansari261:fixes multiple bugs

- web/src/components/HeroImage.jsx
- web/src/pages/Home/Home.jsx
[screen-capture.webm](https://github.com/ArslanYM/StarterHive/assets/12849916/bca4537c-c8e3-48c0-bca8-c32479706627)
bug fixes
floatind div size fixes
> fix: floating div size

- web/src/index.css
- web/src/pages/Home/Home.jsx
> Fix whitespace after footer

- web/src/pages/Home/Home.jsx
#134 
This PR includes the following changes:
The hero container is now centered by adding the `min-h-screen` class to the container element.
As a result, there is additional padding at the top of the hero container.
The footer now only appears when scrolling down the page.
> fix: center hero container vertically

- web/index.html
- web/package-lock.json
- web/package.json
- web/src/pages/Contributors/ContributorItem.jsx
- web/src/pages/Contributors/ContributorsList.jsx
- web/yarn.lock
> feat: Integrated Github API to get contributors

- web/src/layouts/Header.jsx
- web/src/pages/Home/Home.jsx
feat 
added some classes to nav bar link to highlight them
> rahilansari261 active nav link

- web/src/pages/Home/Home.jsx
bug fixes:
floating divs get their height and width
> divs get the height and width

- web/auth.env
- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
- web/src/pages/Contributors/Contributors.jsx
- web/src/pages/Home/Home.jsx
- web/src/pages/Issues/IssuesList.jsx
> feat: added new bg theme gradient

- vercel.json
Fixes #158 
* Added `vercel.json` file to redirect to root URL on visiting any path
> Fix: Vercel - 404 NOT_FOUND

- web/package-lock.json
- web/package.json
- web/src/pages/Contributors/Contributors.jsx
- web/src/pages/Contributors/ContributorsList.jsx
- web/yarn.lock
Fixes #162 
* Implemented Loader Component for Contributors Page
> Add Loader Component

- web/src/pages/Issues/Issue.jsx
- web/src/pages/Issues/IssuesList.jsx
kindly review the redesigned isssue card
> Fixed issue card design

- web/src/layouts/Header.jsx
- web/vercel.json
- web/yarn.lock
> feat: added bold text in the navbar

- README.md
Description:
This pull request adds a new section to the README file specifically targeting frontend developers. The new section encourages frontend developers to contribute to the `web/` directory of the project. It provides information on how to get started with frontend development contributions and invites developers of all skill levels to participate. 
Changes Made:
- Provided instructions on forking the repository, making changes in the `web/` directory, and submitting a pull request.
Why this is valuable:
By specifically inviting front-end developers to contribute, we hope to attract more expertise and creativity in improving the front-end experience of the project. This section serves as a call to action, encouraging developers to explore, enhance, and add new features to the …
> Add Section FrontEnd section in README

- README.md
In the main Readme file, I reviewed and improved the overall organization and visual appearance. Specifically, I focused on making the markup language more consistent and aesthetically pleasing throughout the document. The previous version lacked consistent formatting, which made the Readme less concise and visually appealing.
This change aims to enhance the user experience by providing a more organized and visually coherent Readme. By improving the markup language consistency, users can easily navigate and understand the content of the Readme.
This improvement contributes to better documentation and enhances the overall readability of the project.
Resolves: #174
> Refactor main Readme for better organization and aesthetics.

- CONTRIBUTORS.md
Added my Github profile to list of contributors
> Added profile to Contributors

- web/src/components/HeroImage.jsx
- web/src/index.css
- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
- web/src/pages/Home/Home.jsx
- web/yarn.lock
it solves the below issues and some other issues 
https://github.com/ArslanYM/StarterHive/issues/179
1. fix: below 323px navbar wraps now
2. fix: added a utility class to unset width as we go from sm to md devices
3. fix: margin removed from header logo
4. fix: header logo added
5. fix: hero section text width limited after md devices
6. fix: footer logo and title order changed
> Homepage tweaks for mobile

- web/src/pages/Home/Home.jsx
- web/yarn.lock
> fix: added new pictures to the divs

- README.md
Fixed bug on table of contents not navigating in readme.md file.
> FIX: BUG table of contents not navigating #196

- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
Fixed issue #201
Added necessary spacing in the name at the footer.
> Fix: Fixed project name

- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
it fixes #202
after commiting header part later realised that footer has same issue as well 
so thats why 2 commits
> unwanted margin-left removed from project name from both header and footer

- web/src/App.jsx
- web/src/Context/ThemeContext.jsx
- web/src/components/Switch/Switch.jsx
- web/src/components/Switch/style.css
- web/src/index.css
- web/src/layouts/Footer.jsx
- web/src/layouts/Header.jsx
- web/src/layouts/MasterLayout.jsx
- web/src/pages/Contributors/ContributorItem.jsx
- web/src/pages/Contributors/Contributors.jsx
- web/src/pages/Docs/Guide.jsx
- web/src/pages/Home/Home.jsx
- web/src/pages/Issues/Issue.jsx
- web/src/pages/Issues/IssuesList.jsx
- [ X ] Add dark/light mode to the whole webapp
- [ X ] Add toggle between light mode and dark mode
- [ X ] We should be able to switch between each using a button in the navbar
1. Create a new component call "Switch" wich it is a toggle that fulfills the function of changing to light or dark theme on the Web.
3. Add some CSS Styles for the "Switch" component.
4. Create a new folder call "Context" wich provide to handle the state of the selected theme globally **Dark/Light -> Theme**
5. Saves the user-selected theme to **Web localStorage** so it will be the default theme the next time you visit the site.
6. Provide some colors and background to some components of the project so that they change dynamically according to the theme selected by the user.
> Feat dark/light mode #177

- web/src/layouts/Footer.jsx
issue reference number- #209 
I have fixed the issue.
Now, if we click on footer icon it navigates us to Home.
> Clicking on footer icon navigates to home

- web/src/Context/ThemeContext.jsx
- web/src/layouts/Header.jsx
Feature #184 : Added better UI for Git button in Header
> Header Git button UI changed

- web/src/Context/ThemeContext.jsx
- web/src/pages/Contributors/ContributorsList.jsx
- web/yarn.lock
> Fix Loader component for light theme

- web/src/pages/Issues/IssuesList.jsx
- web/yarn.lock
Fixed it tested on mabile works.
> fixed the white space below the issuestab

- web/src/Context/ThemeContext.jsx
- web/src/layouts/Header.jsx
#214 
This PR removes GitHub btn and replace it with SVG scaling on hover by 5%
> Feat: Replacing GitHub button from header by svg

- CONTRIBUTORS.md
- web/src/Context/ThemeContext.jsx
- web/src/components/Switch/Switch.jsx
- web/src/components/Switch/style.css
- Button appearance changed  
- Added a small animation in the background
https://github.com/ArslanYM/StarterHive/assets/74142173/91a3cdc0-ea01-4a7d-abac-a0a3665f891d
#229
> FEAT: Better looking light/dark Toggle

- web/src/pages/Issues/Issue.jsx
This change resolves #232 by adding links to the labels on the issue card. 
The link would open up the list of open issues under that label.
> Added a link to the labels on the issue card

- web/src/layouts/Header.jsx
> FIX: nav text-font bold for medium devices

- web/src/layouts/Header.jsx
**What l did** 
- Add new JSX elements with NavBar hamburger feature
- Add the funcionality to open and close hamburger menu
> FEAT-NavBar-into-Hamburger

- CONTRIBUTORS.md
- web/src/pages/Contributors/ContributorsList.jsx
- web/src/pages/Contributors/search/Search.jsx
> Feature: Search bar

- web/src/Context/ThemeContext.jsx
- web/src/components/Fab/Fab.jsx
- web/src/hooks/useInterectionObserver.jsx
- web/src/pages/Contributors/Contributors.jsx
- web/src/pages/Docs/Guide.jsx
- web/src/pages/Home/Home.jsx
- web/src/pages/Issues/Issue.jsx
- web/src/pages/Issues/IssuesList.jsx
The button is the `<Fab />` component.
The button looks like this:
Light Mode:
Dark Mode:
I added the button to all the pages except the Home page.
I created a hook using the [intersection observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), to handle the `<Fab />` component, and to handle the components that it needs to observe to show the `<Fab />`
The useIntersectionObserver hook: 
```js
import { useEffect, useRef, useState } from "react";
import PropTypes from "prop-types";
export const useInterectionObserver = (margin = "0px") => {
const [isIntersecting, setIsIntersecting] = useState(false);
const observerRef = useRef(null);
useEffect(() => {
const observer = new IntersectionObserver(
([entry]) => {
setIsIntersecting(entry.isIntersecting);
},
{ …
```
> Feature: back to top botton

- web/src/layouts/Header.jsx
fixes https://github.com/ArslanYM/StarterHive/issues/266
> header alignment fixes

- web/src/layouts/Header.jsx
This PR addresses issue #278 and introduces the following changes:
- Introduced a MENU_ITEMS constant to store menu item data.
- Dynamically generate menu items using the MENU_ITEMS array.
> Refactor navigation menu code for improved scalability

- web/src/layouts/Header.jsx
This pull request addresses issue #267  by resolving a navigation issue and adding an icon for improved user experience.
Changes Made:
* Resolved the navigation issue in the mobile view where the navigation drawer wasn't closing upon clicking a navigation item.
* Updated the hamburger menu icon to a cross "X" icon when the navigation drawer is open.
> fixed: Navigation drawer not closing

- CONTRIBUTORS.md
Added My Name to the list of contributors
> Added Contributor

- web/src/pages/Docs/Guide.jsx
I have updated the Inline css for the subtexts in Docs/Guide.jsx to make text color gray for the docs section. It will be useful for the beginners to understand clearly.  before it is in white color .Users Can't able to see the description of each steps. Below I have attached the testing screenshots for reference.
[## Before](https://starter-hive.vercel.app/docs)
[## After ](https://drive.google.com/file/d/1Hsj-aHyqdJW2CVDfbVKfdxYslr8KwHsR/view?usp=sharing)
```
- <p className="max-w-md text-gray-200" ref={observerRef}>
+ <p className={`max-w-md ${theme.text_Color}`} ref={observerRef}>
\\for every description of the steps in docs paragraph 
- <p className="max-w-md text-neutral-300">
+ <p className={`max-w-md ${theme.text_Color}`}>
```
For further we can discuss or you can compare the …
> Updated Text Color for Light Mode

- CONTRIBUTORS.md
- package-lock.json
- package.json
I forgot to add my name into contributor list. In this PR I just added my name into the contributors list. Can you please merge this pull request ?
> Added my name into the contributor list

- package-lock.json
- web/src/Context/ThemeContext.jsx
- web/src/layouts/Header.jsx
> fixed issue #245

- web/src/pages/Docs/Guide.jsx
Added the changes by updating the Guide.jsx.
> Added the changes

- package-lock.json
- web/src/layouts/Header.jsx
#313 I have added space between navbar links
> Added margin to navbar links 

- web/src/pages/Issues/ListOfOrgs/ProjectCard.jsx
added chips to each project card in the projects section with the tags as values. Additionally added props validation to fix lintr error on ProjectCard.jsx file.
Issue #323
> Added Chips For Tags on Project Cards

- web/src/layouts/Header.jsx
Added a buy-me-a-coffee button in the header.
> feat: added buy-me-a-coffee link in header

- web/src/App.jsx
- web/src/components/ScrollTop.jsx
fixes [bug]: #216 when we click footer link it's navigate to home page and automatically scroll top with smooth animation.
> fixes footer link navigates to home with scroll top

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
issue #332
What does this PR do?
Fixed links for project card logos/images.
Note:
styled-system: image not available for its own repository
Also
Servo : fixed project link
React Native: logo same as for React
> logo rendering fixed

- web/package-lock.json
- web/src/App.jsx
- web/src/pages/Issues/IssueList.jsx
- web/src/pages/Issues/IssuesPage/IssueItem.jsx
- web/src/pages/Issues/IssuesPage/IssueList.jsx
- web/src/pages/Issues/ListOfOrgs/ProjectCard.jsx
- web/yarn.lock
> feat:added issues page with issues of clicked project

- web/src/pages/Issues/ListOfOrgs/ProjectCard.jsx
> Fixed color of text and also made it capitalize 

- web/src/pages/NotFound/NotFound.jsx
The Requested changes for Gradient Fix were fixed in this PR. Also, the scrolling is now stopped in the Desktop and Tablet versions of the Page.
> Gradient & Scrolling Fix in 404Page

- package-lock.json
- web/src/pages/Home/Home.jsx
- web/yarn.lock
Resolved hover effect issue on the React website's home page. 
Fixes #371
- Fixed the hover effect on the "Open Source" text to ensure it no longer impacts the visibility of the word "of."
1. Go to the home page of the website.
2. Hover the mouse cursor over the text "Open Source."
3. Confirm that the hover effect no longer causes visibility issues with the word "of."
🟢 This is my first open source contribution. Please review and merge. 🙂
> fix: Hover effect on "Open Source" affecting visibility of "of" #371

- web/src/pages/Issues/LanguageDropDown.jsx
- web/src/pages/Issues/ProjectList.jsx
Resolve #370 
Now Language sorting alphabetically will be working in production
> Fix: Now Drop Down languages sort in production

- .gitignore
- web/src/index.css
- web/src/pages/Docs/CodeBlock.jsx
- web/src/pages/Docs/Guide.jsx
1. Revamped the design of the documentation page to provide a fresh and modern look.
2. Introduced a `Copy` button to enhance the overall user experience.
Resolve: #343
**Video Preview**
[Watch the video demonstration](https://github.com/ArslanYM/StarterHive/assets/75106349/7541092f-7461-4cd9-b5f4-b5c2eb4e3cbf)
Let me know if any changes are needed. I have tried my best to ensure a smooth and polished user experience.
Thank you!
> Enhance#343: documentation in docs page

- CONTRIBUTORS.md
I included my name as a contributor. 😄
> Included my name at CONTRIBUTORS.md

- CONTRIBUTORS.md
- web/yarn.lock
Adding my github profile to the list of contributors for open source.
> add barkha-gupta

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
Updated the list of projects with new organisations.
> feat: removed old list and updated the list with new projects

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
> feat: Added Cal.com

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
#390 
Added chakra-ui and Next.js to the /projects section
> Feat: Added chakra-ui and Next.js

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
Monkeytype is a open-source minimilist typing practice, testing website with some other features, and i've updated monkeytyping in the code.
Fixes https://github.com/ArslanYM/StarterHive/issues/390
> Corrected Project Name - Monkeytype

- web/src/pages/Issues/ListOfOrgs/listOfOrgs.js
Monkeytype is a open-source minimilist typing practice, testing website with some other features, and i've updated monkeytyping in the code.
Fixes #390
> Adding Another Open Source Project - monkeytype
